import { Document } from 'mongoose';

export type Role = 'SUPER_ADMIN' | 'SUB_ADMIN' | 'B2B_AGENT' | 'SUPPLIER_AGENT' | 'SUPPLIER_STAFF' | 'USER';
export type Department = 'Sales' | 'Operations' | 'Customer Support' | 'Accounts' | null;

export interface IUser extends Document {
  name: string;
  email: string;
  phone?: string;
  password?: string;
  roles: Role[];
  department?: Department;
  companyName?: string | null;
  companyRole?: string;
  supplierOwnerId?: string;
  employeeSize?: string;
  gstn?: string;
  agentStatus?: 'PENDING' | 'PENDING_APPROVAL' | 'APPROVED' | 'REJECTED' | 'INCOMPLETE';
  avatar?: string;
  firstName?: string;
  lastName?: string;
  gender?: 'Male' | 'Female' | 'Other';
  nationality?: string;
  dob?: Date;
  passportNumber?: string;
  passportExpiry?: Date;
  issuingCountry?: string;
  panNumber?: string;
  officeAddress?: string;
  state?: string;
  city?: string;
  pincode?: string;
  panCardImage?: string;
  idProofType?: string;
  idProofImage?: string;
  gstImage?: string;
  remarks?: string;
  isEmailVerified?: boolean;
  isActive: boolean;
  isPhoneVerified?: boolean;
  savedTravellers: {
    firstName: string;
    lastName: string;
    dob: Date;
    gender: 'Male' | 'Female' | 'Other';
    passportNumber?: string;
  }[];
  walletBalance: number;
  creditBalance: number;
  isApproved: boolean;
  resultExpiryTime?: number;
  otpTime?: number;
  requiredTravelDate?: boolean;
  extendedDomain?: string;
  irctcAgentId?: string;
  displayOnProfileIcon?: 'Company Name' | 'User Name' | 'Show Both';
  referredBy?: string;
  reportingTo?: string;
  matchPassword(enteredPassword: string): Promise<boolean>;
  resetPasswordToken?: string;
  resetPasswordExpire?: Date;
  createdAt: Date;
  updatedAt: Date;
}
